### PR TITLE
Add option based on config to disable touchbar from showing

### PR DESCRIPTION
**Pull request by matextrem**
I added the following option in config in order to disable touchbar from showing.

> ```json
> "touchBar": [
> 		{
> 			"command": "npm-script.install",
> 			"group": "navigation@+1",
> 			"when": "config.npm.enableTouchbar"
> 		}
> ```

### CODE REVIEW

**Comment by HenryQW** [comment]
Thank god, this should be merged ASAP.

**Comment by egamma** [comment]
@matextrem (change looks good, but I could not test since I'm currently on Windows).

you should also define the setting in package.json, so that it will be exposed in the UI, here is an example https://github.com/microsoft/vscode-npm-scripts/blob/9bbcf09b46246bdc6ae64ff0e065de379da64bc7/package.json#L164.

Now, the big question is what the default of this setting should be, that is, whether the touch bar actions should be visible by default. Given this comment https://github.com/microsoft/vscode-npm-scripts/pull/77#issuecomment-490712329 I would be defensive set the default to `false`.

**Comment by matextrem** [comment]
@egamma changes done!

**Comment by egamma** [comment]
LGTM, thanks 🌷

**Comment by egamma** [comment]
@matextrem published the new version to the market place.

**Pull request merged**
