### PR TITLE
Use cmd+R as keybinding (fix #1)

### LINKED ISSUE #1: use another key binding prefix than cmd+n
It conflicts with New File and makes New File a chording key binding

### PR DESCRIPTION
**Pull request by gpbl**
I think `R` could be a good key ("run"). What do you think?

### CODE REVIEW

**Comment by egamma** [comment]
I like the suggestion, `R` is better than `N`, my only concern is that I've mapped `cmd+R` to `Reload Window` and others might have done the same. 

Anyways it is an improvement and I'll also add comment to the README.md.

Thanks.

**Comment by gpbl** [comment]
I have no idea how code would handle shortcuts mapped to multiple commands: in your case, which one will win? 🤔
Or maybe just better skip the keybinding at all and let the user choose his/her own 👍 Anything but overwriting `New File` 😃

**Comment by egamma** [comment]
>I have no idea how code would handle shortcuts mapped to multiple commands: in your case, which one will win?

I've defined a customized key binding for 'R` then my customization wins over the extension. Conflicts between extensions is not really defined (well the matching is done bottom-up in the keybindings.json file).

I still like to have an out of the box keybinding that shows how 'chording' can be used for such an extension. `R` is an improvement and I've added a comment to the README with regard to the keybinding.

I've published a new version of the extension to the gallery and there was another publish that I fixed. Thanks for your ping and pull request.

**Comment by gpbl** [comment]
Awesome, thanks to you 🙏

**Pull request merged**
