### PR TITLE
Ability to show status bar item - shortcut to 'Run Script'.

### PR DESCRIPTION
**Pull request by ppluciennik**

### CODE REVIEW

**Comment by ppluciennik** [comment]
I was thinking about showing this status bar just after VSCode has been started.
However it requires change in package.json to "activationEvents": ["*"].
With such change status bar item can appear immediately, and "Activate status bar item" trick won't  be needed.

What do you think about such change?

**Comment by egamma** [comment]
@ppluciennik thanks for this pull request. I've reviewed it and here are my thoughts.

The PR contributes a 'command button' to the status bar that invokes the `npm: Run Scripts`. 

Here are my concerns with using a status bar item like this:
- in general, the status bar should be concerned with showing status and not showing command buttons. This would turn the status bar into a tool bar. Imagine, all extensions would add command buttons to the status bar and use it like a toolbar. This would make the status bar messy (it already has UI scalability limits see also this [extension](https://marketplace.visualstudio.com/items?itemName=GuardRex.status-bar-tasks). 
- the status bar item doesn't show additional status of npm script running, e.g., script running in progress etc. Therefore it has minimal value over the command that is provided by the command palette. This cannot justify the early/ '*' activation of the npm extension.

Given these thoughts, I came to the conclusion to not integrate the PR into the extension at this point in time.

**Comment by ppluciennik** [comment]
I agree with your concerns, however from user's point of view it's more useful to do one click than pressing F1 + typing "npm run script" + Enter.

Extension [python](https://marketplace.visualstudio.com/items?itemName=donjayamanne.python) does the same thing as my PR (actually I've checked how this extension implemented such functionality).

**Comment by egamma** [comment]
>it's more useful to do one click than pressing F1 + typing "npm run script" + Enter.

let's not forget that there is a keybinding for "npm: Run Script" (and users are asking for having custom keybindings for scripts).

>Extension python does the same thing as my PR (actually I've checked how this extension implemented such functionality).

Can you had a screen shot that illustrates this? I can remember that Python shows the testing status in status line and makes the status clickable.

**Comment by ppluciennik** [comment]
Another 

> let's not forget that there is a keybinding for "npm: Run Script" 
Yes, there is, but not very user friendly :)

> Can you had a screen shot that illustrates this? I can remember that Python shows the testing status in status line and makes the status clickable.
Yes it shows status and it's clickable. My solution implements only clickable part (yes I treat status bar as a toolbar).

**Pull request closed without merging**
