### PR TITLE
Add Macbook-Pro's touch bar support

### PR DESCRIPTION
**Pull request by matextrem**
Add support for Macbook-pro's touch bar for the most commonly used commands.

touchbar-support

You can run the following commands: 
- npm install
- npm start
- npm test
- npm build

### CODE REVIEW

**Comment by matextrem** [comment]
@egamma

**Comment by egamma** [comment]
@matextrem sorry I was heads down working the vscode-remote stuff. Will look into this this week.

**Comment by egamma** [comment]
@matextrem this looks interesting.

Some feedback:
- it looks like you changed the format of the package.json and the diff shows everything as changed, which makes it difficult to review. Please fix the formatting.
- please exclude assets/.DS_Store from the PR.

**Comment by matextrem** [comment]
@egamma Thanks you so much for your feedback! I have recently updated the PR with the changes you requested.

**Comment by egamma** [comment]
LGTM, thanks!

**Comment by egamma** [comment]
Published to the market place.

**Comment by Coollision** [comment]
is there an option do disable these touchbar options form showing?

**Comment by egamma** [comment]
@Coollision currently not, but it would make sense to provide a setting to disable the touchbar contributions.

@matextrem it is pretty straightforward to support this. Would you be willing to enrich the PR?

I suggest to add a setting `npm.enableTouchbar`. You can then enable the touch bar depending on the value of this setting using a `when` clause:
```json
"touchBar": [
		{
			"command": "npm-script.install",
			"group": "navigation@+1",
			"when": "config.npm.enableTouchbar"
		}
```

**Comment by Coollision** [comment]
@egamma Thanks for the info, I am looking forward to the update.

**Comment by matextrem** [comment]
@egamma I will do it ASAP!

@Coollision Thank you for your feedback!

**Comment by jlw8ke** [comment]
Being able to enable/disable the touchbar would be a welcome change.  For me, I was using [NASC](https://marketplace.visualstudio.com/items?itemName=felipe.nasc-touchbar) to configure the touchbar to my liking.  It would be nice to be able to use the npm extension, while keeping my old touchbar configuration.

**Comment by chrislim** [comment]
When I do the build command, I get this error:
<pre>
npm WARN build `npm build` called with no arguments. Did you mean to `npm run-script build`?
</pre>

Should `npm build` be `npm run build`?

I think the change needs to be made to this line: https://github.com/microsoft/vscode-npm-scripts/blob/2c0a0657655d02d35d9570f6e2da70133b8ea1f3/src/main.ts#L469

**Pull request merged**
