### PR TITLE
Fixed problem with not respecting npm.includeDirectories.

### PR DESCRIPTION
**Pull request by ppluciennik**
Extra directories were not used by runNpn* functions.
Extended code to give ability to run one or all scripts that matches given name.

This change should fix issue 24 (https://github.com/Microsoft/vscode-npm-scripts/issues/24) and extend module to give option to run multiple scripts that have the same name (but located in different package.json).

### CODE REVIEW

**Comment by ppluciennik** [comment]
@egamma: Could you have a look at my changes?

**Comment by egamma** [comment]
@ppluciennik thanks for the PR, I'll take a look at them later today.

**Comment by egamma** [comment]
@ppluciennik have you tested this with having the setting `npm.runInTerminal` set to both `true` and `false`? According to this comment https://github.com/Microsoft/vscode-npm-scripts/issues/24#issuecomment-261794106 the code behaves differently when it is run in the integrated terminal or not.

**Comment by ppluciennik** [comment]
I've added new fix for npm.runInTerminal=true. There was a problem that in terminal command were executed in a wrong directory.

**Comment by ppluciennik** [comment]
I'll do more testing to be sure that code fixes all use cases.

**Comment by egamma** [comment]
@ppluciennik sounds good thanks. 

Since we have no automated tests yet, I was thinking that we could at least create some manual test setups in the repository, That we then exclude from bundled with the extension. 

I'm thinking of something like this:

```
tests
   test-includeDirectories  // this folder is opened in VS Code to run the manual test
       test.md  // describes the manual test steps
       .vscode
           settings.json  // settings for the test case
       folder1
           package.json
       folder2
           package.json
```
What do you think?

**Comment by ppluciennik** [comment]
Sounds good to me. I'll include it in this review.

I don't know how to trigger these commands:
- npm-script.install,
- npm-script.installInOutputWindow,
- npm-script.uninstallInOutputWindow,
- npm-script.validate

Could you give me a hint how to invoke them from UI?

**Comment by ppluciennik** [comment]
I think I've finished my work regarding this pull request. @egamma please review it and raise issues if you feel something has to be improved.

**Comment by egamma** [comment]
@ppluciennik thanks! I'll look into this soon (I'm currently also the [inbox tracker](https://github.com/Microsoft/vscode/wiki/Issue-Tracking#inbox-tracking-and-issue-triage) and that keeps me busy...)

**Comment by egamma** [comment]
@ppluciennik this looks like good work. I've merged the change and I'll start the review.

**Comment by egamma** [comment]
@ppluciennik I made a review pass and the changes looks good. I've made a general pass to remove `implicit anys` and added some lint rules, thanks again.

**Pull request merged**
